### ISSUE TITLE
.getUrnWithoutSubref() method for CTS-URNs

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/cite#55]
E.g.

urn:cts:greekLit:tlg0012.tlg001.msA:1.1@μ[1] --> urn:cts:greekLit:tlg0012.tlg001.msA:1.1
urn:cts:greekLit:tlg0012.tlg001.msA:1.1@μ[1]-1.2@οὐλομένην --> urn:cts:greekLit:tlg0012.tlg001.msA:1.1-1.2

**Comment by neelsmith** [comment]
New method String reduceToNode() implemented and unit tested.
