### ISSUE TITLE
.hasSubref() for CITE URNs

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/cite#58]
We need this.

**Comment by neelsmith** [comment]
THere is already a methods boolean hasExtendedRef() to test  whether an individual object has an extended ref.

THere are also methods to retrieve extended references on either part of a range.

Docs here http://cite-architecture.github.io/cite/api/ are a little out of date today, but API docs and specs in the repository are not bad.

I'm closing this issue for now -- if we need boolean hasExtendedRef() on a range URN, I'll happily open a new issue, but first need to determine what that boolean woud/should tell us.
